//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepChat.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StepChat.ServiceReference1.ResultOfArrayOfUserQo1Oyztf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StepChat.ServiceReference1.ResultOfChatQo1Oyztf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StepChat.ServiceReference1.ResultOfArrayOfChatQo1Oyztf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StepChat.ServiceReference1.ResultOfMessageQo1Oyztf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StepChat.ServiceReference1.ResultOfArrayOfMessageQo1Oyztf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StepChat.ServiceReference1.ResultOfUserQo1Oyztf))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StepChat.ServiceReference1.ResultError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StepChat.ServiceReference1.ResultError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfArrayOfUserQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfArrayOfUserQo1Oyztf : StepChat.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StepChat.ServiceReference1.User[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StepChat.ServiceReference1.User[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfChatQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfChatQo1Oyztf : StepChat.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StepChat.ServiceReference1.Chat DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StepChat.ServiceReference1.Chat Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfArrayOfChatQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfArrayOfChatQo1Oyztf : StepChat.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StepChat.ServiceReference1.Chat[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StepChat.ServiceReference1.Chat[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfMessageQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfMessageQo1Oyztf : StepChat.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StepChat.ServiceReference1.Message DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StepChat.ServiceReference1.Message Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfArrayOfMessageQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfArrayOfMessageQo1Oyztf : StepChat.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StepChat.ServiceReference1.Message[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StepChat.ServiceReference1.Message[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfUserQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfUserQo1Oyztf : StepChat.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StepChat.ServiceReference1.User DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StepChat.ServiceReference1.User Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultError", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public enum ResultError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Null = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginIsUsed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotExist = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChatNotExist = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordIsIncorrect = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotImplemented = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAuthorized = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Service.DTO")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastOnlineDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoPathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bio {
            get {
                return this.BioField;
            }
            set {
                if ((object.ReferenceEquals(this.BioField, value) != true)) {
                    this.BioField = value;
                    this.RaisePropertyChanged("Bio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastOnlineDate {
            get {
                return this.LastOnlineDateField;
            }
            set {
                if ((this.LastOnlineDateField.Equals(value) != true)) {
                    this.LastOnlineDateField = value;
                    this.RaisePropertyChanged("LastOnlineDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoPath {
            get {
                return this.PhotoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoPathField, value) != true)) {
                    this.PhotoPathField = value;
                    this.RaisePropertyChanged("PhotoPath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chat", Namespace="http://schemas.datacontract.org/2004/07/Service.DTO")]
    [System.SerializableAttribute()]
    public partial class Chat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReadStatusIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPersonal {
            get {
                return this.IsPersonalField;
            }
            set {
                if ((this.IsPersonalField.Equals(value) != true)) {
                    this.IsPersonalField = value;
                    this.RaisePropertyChanged("IsPersonal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoPath {
            get {
                return this.PhotoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoPathField, value) != true)) {
                    this.PhotoPathField = value;
                    this.RaisePropertyChanged("PhotoPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReadStatusId {
            get {
                return this.ReadStatusIdField;
            }
            set {
                if ((this.ReadStatusIdField.Equals(value) != true)) {
                    this.ReadStatusIdField = value;
                    this.RaisePropertyChanged("ReadStatusId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Service.DTO")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChatId {
            get {
                return this.ChatIdField;
            }
            set {
                if ((this.ChatIdField.Equals(value) != true)) {
                    this.ChatIdField = value;
                    this.RaisePropertyChanged("ChatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((this.SenderIdField.Equals(value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        StepChat.ServiceReference1.ResultOfUserQo1Oyztf Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfUserQo1Oyztf> LoginAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Register", ReplyAction="http://tempuri.org/IService/RegisterResponse")]
        StepChat.ServiceReference1.ResultOfUserQo1Oyztf Register(StepChat.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Register", ReplyAction="http://tempuri.org/IService/RegisterResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfUserQo1Oyztf> RegisterAsync(StepChat.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditUserInfo", ReplyAction="http://tempuri.org/IService/EditUserInfoResponse")]
        StepChat.ServiceReference1.ResultOfUserQo1Oyztf EditUserInfo(StepChat.ServiceReference1.User newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditUserInfo", ReplyAction="http://tempuri.org/IService/EditUserInfoResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfUserQo1Oyztf> EditUserInfoAsync(StepChat.ServiceReference1.User newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ChangePassword", ReplyAction="http://tempuri.org/IService/ChangePasswordResponse")]
        StepChat.ServiceReference1.Result ChangePassword(string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ChangePassword", ReplyAction="http://tempuri.org/IService/ChangePasswordResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.Result> ChangePasswordAsync(string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddContact", ReplyAction="http://tempuri.org/IService/AddContactResponse")]
        StepChat.ServiceReference1.Result AddContact(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddContact", ReplyAction="http://tempuri.org/IService/AddContactResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.Result> AddContactAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetContacts", ReplyAction="http://tempuri.org/IService/GetContactsResponse")]
        StepChat.ServiceReference1.ResultOfArrayOfUserQo1Oyztf GetContacts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetContacts", ReplyAction="http://tempuri.org/IService/GetContactsResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfArrayOfUserQo1Oyztf> GetContactsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SearchUsers", ReplyAction="http://tempuri.org/IService/SearchUsersResponse")]
        StepChat.ServiceReference1.ResultOfArrayOfUserQo1Oyztf SearchUsers(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SearchUsers", ReplyAction="http://tempuri.org/IService/SearchUsersResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfArrayOfUserQo1Oyztf> SearchUsersAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreatePrivateChat", ReplyAction="http://tempuri.org/IService/CreatePrivateChatResponse")]
        StepChat.ServiceReference1.ResultOfChatQo1Oyztf CreatePrivateChat(int withUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreatePrivateChat", ReplyAction="http://tempuri.org/IService/CreatePrivateChatResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfChatQo1Oyztf> CreatePrivateChatAsync(int withUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateChat", ReplyAction="http://tempuri.org/IService/CreateChatResponse")]
        StepChat.ServiceReference1.ResultOfChatQo1Oyztf CreateChat(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateChat", ReplyAction="http://tempuri.org/IService/CreateChatResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfChatQo1Oyztf> CreateChatAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/JoinChat", ReplyAction="http://tempuri.org/IService/JoinChatResponse")]
        StepChat.ServiceReference1.ResultOfChatQo1Oyztf JoinChat(int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/JoinChat", ReplyAction="http://tempuri.org/IService/JoinChatResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfChatQo1Oyztf> JoinChatAsync(int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LeaveChat", ReplyAction="http://tempuri.org/IService/LeaveChatResponse")]
        StepChat.ServiceReference1.Result LeaveChat(int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LeaveChat", ReplyAction="http://tempuri.org/IService/LeaveChatResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.Result> LeaveChatAsync(int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetChats", ReplyAction="http://tempuri.org/IService/GetChatsResponse")]
        StepChat.ServiceReference1.ResultOfArrayOfChatQo1Oyztf GetChats();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetChats", ReplyAction="http://tempuri.org/IService/GetChatsResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfArrayOfChatQo1Oyztf> GetChatsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendMessage", ReplyAction="http://tempuri.org/IService/SendMessageResponse")]
        StepChat.ServiceReference1.ResultOfMessageQo1Oyztf SendMessage(int chatId, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendMessage", ReplyAction="http://tempuri.org/IService/SendMessageResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfMessageQo1Oyztf> SendMessageAsync(int chatId, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditMessage", ReplyAction="http://tempuri.org/IService/EditMessageResponse")]
        StepChat.ServiceReference1.ResultOfMessageQo1Oyztf EditMessage(int messageId, string newText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditMessage", ReplyAction="http://tempuri.org/IService/EditMessageResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfMessageQo1Oyztf> EditMessageAsync(int messageId, string newText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMessage", ReplyAction="http://tempuri.org/IService/DeleteMessageResponse")]
        StepChat.ServiceReference1.Result DeleteMessage(int messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMessage", ReplyAction="http://tempuri.org/IService/DeleteMessageResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.Result> DeleteMessageAsync(int messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMessages", ReplyAction="http://tempuri.org/IService/GetMessagesResponse")]
        StepChat.ServiceReference1.ResultOfArrayOfMessageQo1Oyztf GetMessages(int chatId, int offset, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMessages", ReplyAction="http://tempuri.org/IService/GetMessagesResponse")]
        System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfArrayOfMessageQo1Oyztf> GetMessagesAsync(int chatId, int offset, int size);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : StepChat.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<StepChat.ServiceReference1.IService>, StepChat.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StepChat.ServiceReference1.ResultOfUserQo1Oyztf Login(string login1, string password) {
            return base.Channel.Login(login1, password);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfUserQo1Oyztf> LoginAsync(string login, string password) {
            return base.Channel.LoginAsync(login, password);
        }
        
        public StepChat.ServiceReference1.ResultOfUserQo1Oyztf Register(StepChat.ServiceReference1.User user) {
            return base.Channel.Register(user);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfUserQo1Oyztf> RegisterAsync(StepChat.ServiceReference1.User user) {
            return base.Channel.RegisterAsync(user);
        }
        
        public StepChat.ServiceReference1.ResultOfUserQo1Oyztf EditUserInfo(StepChat.ServiceReference1.User newUser) {
            return base.Channel.EditUserInfo(newUser);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfUserQo1Oyztf> EditUserInfoAsync(StepChat.ServiceReference1.User newUser) {
            return base.Channel.EditUserInfoAsync(newUser);
        }
        
        public StepChat.ServiceReference1.Result ChangePassword(string newPassword) {
            return base.Channel.ChangePassword(newPassword);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.Result> ChangePasswordAsync(string newPassword) {
            return base.Channel.ChangePasswordAsync(newPassword);
        }
        
        public StepChat.ServiceReference1.Result AddContact(int userId) {
            return base.Channel.AddContact(userId);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.Result> AddContactAsync(int userId) {
            return base.Channel.AddContactAsync(userId);
        }
        
        public StepChat.ServiceReference1.ResultOfArrayOfUserQo1Oyztf GetContacts() {
            return base.Channel.GetContacts();
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfArrayOfUserQo1Oyztf> GetContactsAsync() {
            return base.Channel.GetContactsAsync();
        }
        
        public StepChat.ServiceReference1.ResultOfArrayOfUserQo1Oyztf SearchUsers(string query) {
            return base.Channel.SearchUsers(query);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfArrayOfUserQo1Oyztf> SearchUsersAsync(string query) {
            return base.Channel.SearchUsersAsync(query);
        }
        
        public StepChat.ServiceReference1.ResultOfChatQo1Oyztf CreatePrivateChat(int withUserId) {
            return base.Channel.CreatePrivateChat(withUserId);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfChatQo1Oyztf> CreatePrivateChatAsync(int withUserId) {
            return base.Channel.CreatePrivateChatAsync(withUserId);
        }
        
        public StepChat.ServiceReference1.ResultOfChatQo1Oyztf CreateChat(string name) {
            return base.Channel.CreateChat(name);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfChatQo1Oyztf> CreateChatAsync(string name) {
            return base.Channel.CreateChatAsync(name);
        }
        
        public StepChat.ServiceReference1.ResultOfChatQo1Oyztf JoinChat(int chatId) {
            return base.Channel.JoinChat(chatId);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfChatQo1Oyztf> JoinChatAsync(int chatId) {
            return base.Channel.JoinChatAsync(chatId);
        }
        
        public StepChat.ServiceReference1.Result LeaveChat(int chatId) {
            return base.Channel.LeaveChat(chatId);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.Result> LeaveChatAsync(int chatId) {
            return base.Channel.LeaveChatAsync(chatId);
        }
        
        public StepChat.ServiceReference1.ResultOfArrayOfChatQo1Oyztf GetChats() {
            return base.Channel.GetChats();
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfArrayOfChatQo1Oyztf> GetChatsAsync() {
            return base.Channel.GetChatsAsync();
        }
        
        public StepChat.ServiceReference1.ResultOfMessageQo1Oyztf SendMessage(int chatId, string text) {
            return base.Channel.SendMessage(chatId, text);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfMessageQo1Oyztf> SendMessageAsync(int chatId, string text) {
            return base.Channel.SendMessageAsync(chatId, text);
        }
        
        public StepChat.ServiceReference1.ResultOfMessageQo1Oyztf EditMessage(int messageId, string newText) {
            return base.Channel.EditMessage(messageId, newText);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfMessageQo1Oyztf> EditMessageAsync(int messageId, string newText) {
            return base.Channel.EditMessageAsync(messageId, newText);
        }
        
        public StepChat.ServiceReference1.Result DeleteMessage(int messageId) {
            return base.Channel.DeleteMessage(messageId);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.Result> DeleteMessageAsync(int messageId) {
            return base.Channel.DeleteMessageAsync(messageId);
        }
        
        public StepChat.ServiceReference1.ResultOfArrayOfMessageQo1Oyztf GetMessages(int chatId, int offset, int size) {
            return base.Channel.GetMessages(chatId, offset, size);
        }
        
        public System.Threading.Tasks.Task<StepChat.ServiceReference1.ResultOfArrayOfMessageQo1Oyztf> GetMessagesAsync(int chatId, int offset, int size) {
            return base.Channel.GetMessagesAsync(chatId, offset, size);
        }
    }
}
